### ISSUE TITLE
[FEAT]: Add git to alpine image

### ISSUE THREAD

**Issue by RodrigoTomeES** [ImBIOS/bun-node#16]
### Clear and concise description of the problem

Hi,

I am trying to execute chromatic with turbosnap in alpine image but I can't because it wouldn't have git, so if would be great if this image can has git

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ImBIOS/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ImBIOS/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ImBIOS** [comment]
@RodrigoTomeES Is using a multi-stage build not enough? Can you push and share a minimum reproducible repository for me, so I can understand more of your requirements?

Example:

```dockerfile
FROM imbios/bun-node:latest-hydrogen-alpine
# build stage here

FROM alpine/git:user
# runtime stage here
```

**Comment by RodrigoTomeES** [comment]
@ImBIOS is for a bitbcuket pipeline so I can't not build an image for the pipeline I can only use it, right now I am using the debian image because it has git. My code is something like this:

```yaml
pipelines:
  branches:
    master:
      - step:
        name: deploy chromatic
        image: imbios/bun-node:latest-18-debian
        script:
          - bun install
          - bunx chromatic
 ```
